version: "3.8"

services:
  traefik:
    image: "traefik:v2.11"
    ports:
      - "80:80"
    environment:
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_LOG_LEVEL=DEBUG
      - TRAEFIK_PROVIDERS_DOCKER_WATCH=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_HTTP_ROUTERS_API_RULE=Host(`traefik.localtest.me`)
      - TRAEFIK_HTTP_ROUTERS_API_ENTRYPOINTS=web
      - TRAEFIK_HTTP_ROUTERS_API_SERVICE=api@internal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - minio_net

  minio: 
    image: minio/minio 
    environment: 
      MINIO_ROOT_USER: minioadmin 
      MINIO_ROOT_PASSWORD: minioadmin 
    command: ["server", "--console-address", ":9001", "/data"]
    ports: 
      - "9000:9000" 
    networks: 
      - minio_net

  download:
    build:
      context: .
      dockerfile: Dockerfile
      target: download
    volumes:
      - ./api:/cs480-f24-final-project/api
    environment:
      - S3_ENDPOINT=minio:9000
      - ACCESS_KEY=minioadmin 
      - SECRET_KEY=minioadmin 
    labels:
      - traefik.http.routers.download.rule=Host(`localtest.me`) && PathPrefix(`/download`)
    networks:
      - minio_net

  list:
    build:
      context: .
      dockerfile: Dockerfile
      target: list
    environment:
      - S3_ENDPOINT=minio:9000
      - ACCESS_KEY=minioadmin 
      - SECRET_KEY=minioadmin 
    volumes:
      - ./api:/cs480-f24-final-project/api
    labels:
      - traefik.http.routers.list.rule=Host(`localtest.me`) && PathPrefix(`/list`)
    networks:
      - minio_net

  upload:
    build:
      context: .
      dockerfile: Dockerfile
      target: upload
    environment:
      - S3_ENDPOINT=minio:9000
      - ACCESS_KEY=minioadmin 
      - SECRET_KEY=minioadmin 
    volumes:
      - ./api:/cs480-f24-final-project/api
    labels:
      - traefik.http.routers.upload.rule=Host(`localtest.me`) && PathPrefix(`/upload`)
    networks:
      - minio_net

networks: 
  minio_net:
