# This Compose file builds two services - "login" and "user" - and exposes each independently.
version: "3.8"

services:
  download:
    build: # this section specifies the context (working directory), the Dockerfile name itself, and the *target* to build for this service.
      context: .
      dockerfile: Dockerfile
      target: download
    volumes:
    - ./api:/cs480-f24-final-project/api
    ports:
      - "5000:5000"
  list:
    build:
      context: .
      dockerfile: Dockerfile
      target: list
    volumes:
    - ./api:/cs480-f24-final-project/api
    ports:
      - "5001:5000"
  upload:
    build:
      context: .
      dockerfile: Dockerfile
      target: upload
    volumes:
    - ./api:/cs480-f24-final-project/api
    ports:
      - "5002:5000"
