# This Compose file builds two services - "login" and "user" - and exposes each independently.

services:
  download:
    build: # this section specifies the context (working directory), the Dockerfile name itself, and the *target* to build for this service.
      context: .
      dockerfile: Dockerfile
      target: download
    ports:
      - "5000:5000"
  list:
    build:
      context: .
      dockerfile: Dockerfile
      target: list
    ports:
      - "5001:5000"
  upload:
    build:
      context: .
      dockerfile: Dockerfile
      target: upload
    ports:
      - "5002:5000"
