version: "3.8"

services:
  traefik:
    image: "traefik:v2.11"
    ports:
      - "80:80"
    environment:
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_LOG_LEVEL=DEBUG
      - TRAEFIK_PROVIDERS_DOCKER_WATCH=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_HTTP_ROUTERS_API_RULE=Host(`traefik.localtest.me`)
      - TRAEFIK_HTTP_ROUTERS_API_ENTRYPOINTS=web
      - TRAEFIK_HTTP_ROUTERS_API_SERVICE=api@internal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  download:
    build:
      context: .
      dockerfile: Dockerfile
      target: download
    volumes:
      - ./api:/cs480-f24-final-project/api
    labels:
      - traefik.http.routers.download.rule=Host(`localtest.me`) && PathPrefix(`/download`)

  list:
    build:
      context: .
      dockerfile: Dockerfile
      target: list
    volumes:
      - ./api:/cs480-f24-final-project/api
    labels:
      - traefik.http.routers.list.rule=Host(`localtest.me`) && PathPrefix(`/list`)

  upload:
    build:
      context: .
      dockerfile: Dockerfile
      target: upload
    volumes:
      - ./api:/cs480-f24-final-project/api
    labels:
      - traefik.http.routers.upload.rule=Host(`localtest.me`) && PathPrefix(`/upload`)

